version: '3.7'
services:
  local-stack-aws:
    image: 'localstack/localstack'
    container_name: 'local-stack-aws'
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4566:4566'
    volumes:
      - ./docker-files/config:/root/.aws/config
      - ./docker-files/credentials:/root/.aws/credentials
  redis-local:
    image: "redis"
    container_name: 'redis-local'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
